import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import DisplayLayout from "@/components/DisplayLayout";

const geistSans = localFont({
  variable: "--font-geist-sans",
  src: [
    { path: "../public/fonts/campton/CamptonBook.otf", weight: "400", style: "normal" },
    { path: "../public/fonts/campton/CamptonBold.otf", weight: "700", style: "normal" },
  ],
});

const geistMono = localFont({
  variable: "--font-geist-mono",
  src: [
    { path: "../public/fonts/campton/CamptonMedium.otf", weight: "500", style: "normal" },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <DisplayLayout>{children}</DisplayLayout>
      </body>
    </html>
  );
}
